#!/usr/bin/env python3
# Project imports

# Python imports

# 3rd-party imports
import rospy
## ROS Service Definitions 
from std_srvs.srv import Empty, EmptyResponse

""" 
General Description of setup
"""
# Where the bulk of the work happens
class Setup:
    def __init__(self):
        self.waypoints = rospy.get_param("turtle_control/waypoints")
        for p in self.waypoints:
            print(p)
            rospy.loginfo(p)

#Activate 'setup' node
def main():
    rospy.init_node('setup')
    setup = Setup()
    rospy.spin()

# Main Execution loop
if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass